[project]
name = "my-python-standards"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dewashington33", email = "dewashington@hotmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
]

[project.scripts]
my-python-standards = "my_python_standards:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]
